refactor: posts services
ivanmosa27/blog-net-core pull request #1
Opened 2021-11-25 12:56 UTC by ivanmosa27

This refactor change: 
-The routes naming.
-Implement the posts services following the SOLID principes.

2021-11-26 11:50 UTC, danielhdezller requested changes
great job!

2021-11-26 11:50 UTC, danielhdezller commented on Controllers/PostsController.cs
> +    [Route("[controller]")]
here should be "posts"

2021-11-26 11:50 UTC, danielhdezller commented on Controllers/PostsController.cs
> +            _blogService = blogService;
its the postService, the blog could be an entity that manage the relations of many posts

2021-11-26 11:50 UTC, danielhdezller commented on Properties/launchSettings.json
> +      "launchUrl": "posts",
the launchUrl should not be the controller route

2021-11-26 11:50 UTC, danielhdezller commented on Services/blogService.cs
> +        private readonly BLOGContext _context;
It's not BLOG always use camel case, it's the PostsContext

2021-11-26 11:50 UTC, danielhdezller commented on Startup.cs
> +            services.AddTransient<IBlogService, blogService>();
IPostsService

2021-12-17 08:43 UTC, closed without merging

2021-12-17 08:43 UTC, ivanmosa27 commented
Closed